version: "3.3"

services:
  traefik:
    image: traefik:v2.2
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
    ports:
      - "80:80"
      - "8080:8080"
    restart: always
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  api:
    image: alfg/overwatch-api:latest
    container_name: "api"
    ports:
      - "3000"
    environment:
      - "CACHE_TTL=1200"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`owapi.docker.localhost`, `owapi.io`, `www.owapi.io`, `api.owapi.io`)"
      - "traefik.http.routers.api.entrypoints=web"
      - "traefik.http.services.api.loadbalancer.server.port=3000"
      - "traefik.http.routers.api.middlewares=ratelimit"
      - "traefik.http.middlewares.ratelimit.ratelimit.average=20"
      - "traefik.http.middlewares.ratelimit.ratelimit.burst=15"
    restart: always